// <auto-generated />
using System;
using Crypto_Lab.DAL.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crypto_Lab.DAL.Migrations
{
    [DbContext(typeof(CryptoDbContext))]
    [Migration("20231228223202_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Crypto_Lab.Common.Models.Exchanges.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0)
                        .HasComment("主鍵");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fiats")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fiats")
                        .HasColumnOrder(4)
                        .HasComment("交易所可兌換法定貨幣(JSON)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdated")
                        .HasColumnOrder(5)
                        .HasComment("最後更新時間");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name")
                        .HasColumnOrder(1)
                        .HasComment("交易所名稱");

                    b.Property<string>("NumMarketPairs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NumMarketPairs")
                        .HasColumnOrder(3)
                        .HasComment("市場上交易對數量");

                    b.Property<string>("Slug")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Slug")
                        .HasColumnOrder(2)
                        .HasComment("交易所名稱");

                    b.HasKey("Id");

                    b.ToTable("TblExchanges", (string)null);
                });

            modelBuilder.Entity("Crypto_Lab.Common.Models.MarketPairs.MarketPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0)
                        .HasComment("主鍵");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BaseAsset")
                        .HasColumnOrder(3)
                        .HasComment("交易對象");

                    b.Property<string>("ExchangeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ExchangeName")
                        .HasColumnOrder(2)
                        .HasComment("交易所名稱");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name")
                        .HasColumnOrder(1)
                        .HasComment("交易所名稱");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 9)")
                        .HasColumnName("Price")
                        .HasColumnOrder(5)
                        .HasComment("價格");

                    b.Property<string>("QuoteAsset")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QuoteAsset")
                        .HasColumnOrder(4)
                        .HasComment("定價資產");

                    b.HasKey("Id");

                    b.ToTable("TblMarketPairs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
